# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnAlphaijLogLik <- function(alpha_ij, mu_ij_vec, s_j, lambda_ij, eta_ell, w_ell, upsilon_alpha, u_2, y_ij_vec, delta_ij_vec) {
    .Call(`_bnpzimnr_fnAlphaijLogLik`, alpha_ij, mu_ij_vec, s_j, lambda_ij, eta_ell, w_ell, upsilon_alpha, u_2, y_ij_vec, delta_ij_vec)
}

fnSampAlphaMat <- function(Alpha_mat, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_alpha, u_2, Y_mat, Delta_mat, alpha_ij_proposal_sd) {
    .Call(`_bnpzimnr_fnSampAlphaMat`, Alpha_mat, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_alpha, u_2, Y_mat, Delta_mat, alpha_ij_proposal_sd)
}

fnSampBetaMat <- function(Beta_mat, Mu_mat, Delta_mat, s_vec, tau_2_vec, X_mat, Y_mat, rep_K, beta_j_proposal_sd_vec) {
    .Call(`_bnpzimnr_fnSampBetaMat`, Beta_mat, Mu_mat, Delta_mat, s_vec, tau_2_vec, X_mat, Y_mat, rep_K, beta_j_proposal_sd_vec)
}

fnSampDeltaMat <- function(Delta_mat, Epsilon_mat, Theta_mat, C_theta_mat, d_theta_vec, Theta_star_mat, psi_theta_vec, sigma_2_theta_vec, Alpha_mat, r_vec, s_vec, Mu_mat, Y_mat, condition, subject, theta_kj_proposal_sd, psi_alpha_vec, w_alpha_vec, eta_alpha_vec, c_alpha_vec, d_alpha_vec, lambda_alpha_vec, rep_K, Xtbeta_mat, upsilon_alpha, u_alpha_2) {
    .Call(`_bnpzimnr_fnSampDeltaMat`, Delta_mat, Epsilon_mat, Theta_mat, C_theta_mat, d_theta_vec, Theta_star_mat, psi_theta_vec, sigma_2_theta_vec, Alpha_mat, r_vec, s_vec, Mu_mat, Y_mat, condition, subject, theta_kj_proposal_sd, psi_alpha_vec, w_alpha_vec, eta_alpha_vec, c_alpha_vec, d_alpha_vec, lambda_alpha_vec, rep_K, Xtbeta_mat, upsilon_alpha, u_alpha_2)
}

fnStickBreak <- function(weights) {
    .Call(`_bnpzimnr_fnStickBreak`, weights)
}

fnSampStarMatCommon <- function(Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc, truncated, lower, upper) {
    .Call(`_bnpzimnr_fnSampStarMatCommon`, Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc, truncated, lower, upper)
}

fnSampStarMat <- function(Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc) {
    .Call(`_bnpzimnr_fnSampStarMat`, Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc)
}

fnSampStarMatTrunc <- function(Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc, lower, upper) {
    .Call(`_bnpzimnr_fnSampStarMatTrunc`, Param_mat, C_mat, sigma_2_vec, a_star, b_star_2, L_trunc, lower, upper)
}

fnCProbs <- function(param_kj, psi_vec, Param_star_k_vec, sigma_k_2) {
    .Call(`_bnpzimnr_fnCProbs`, param_kj, psi_vec, Param_star_k_vec, sigma_k_2)
}

fnSampCMat <- function(C_mat, Param_mat, d_vec, psi_vec, Param_star_mat, sigma_2_vec) {
    .Call(`_bnpzimnr_fnSampCMat`, C_mat, Param_mat, d_vec, psi_vec, Param_star_mat, sigma_2_vec)
}

fnSampXiMat <- function(Xi_mat, Epsilon_mat, Delta_mat, Xi_star_mat, C_xi_mat, sigma_2_xi_vec, condition, xi_kj_proposal_sd) {
    .Call(`_bnpzimnr_fnSampXiMat`, Xi_mat, Epsilon_mat, Delta_mat, Xi_star_mat, C_xi_mat, sigma_2_xi_vec, condition, xi_kj_proposal_sd)
}

fnSampXiMatMarg <- function(Xi_mat, Epsilon_mat, Delta_mat, Xi_star_mat, psi_xi_vec, sigma_2_xi_vec, condition, xi_kj_proposal_sd) {
    .Call(`_bnpzimnr_fnSampXiMatMarg`, Xi_mat, Epsilon_mat, Delta_mat, Xi_star_mat, psi_xi_vec, sigma_2_xi_vec, condition, xi_kj_proposal_sd)
}

fnLogLik <- function(y_ikj, s_j, mu_ikj, delta_ikj) {
    .Call(`_bnpzimnr_fnLogLik`, y_ikj, s_j, mu_ikj, delta_ikj)
}

fnOtuLogLik <- function(s_j, mu_j_vec, rep_K, y_j_vec, delta_j_vec) {
    .Call(`_bnpzimnr_fnOtuLogLik`, s_j, mu_j_vec, rep_K, y_j_vec, delta_j_vec)
}

fnSampleLogLikNoGamma <- function(mu_ik_vec, s_vec, y_ik_vec, delta_ik_vec) {
    .Call(`_bnpzimnr_fnSampleLogLikNoGamma`, mu_ik_vec, s_vec, y_ik_vec, delta_ik_vec)
}

fnRepLogLik <- function(mu_ij_vec, s_j, y_ij_vec, delta_ij_vec) {
    .Call(`_bnpzimnr_fnRepLogLik`, mu_ij_vec, s_j, y_ij_vec, delta_ij_vec)
}

fnSubjectLogLik <- function(k, y_j_vec, s_j, mu_j_vec, delta_j_vec, condition) {
    .Call(`_bnpzimnr_fnSubjectLogLik`, k, y_j_vec, s_j, mu_j_vec, delta_j_vec, condition)
}

fnWlLogLik <- function(ell_idx1, w_ell, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2) {
    .Call(`_bnpzimnr_fnWlLogLik`, ell_idx1, w_ell, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2)
}

fnSampWVec <- function(w_vec, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2, w_vec_proposal_sd) {
    .Call(`_bnpzimnr_fnSampWVec`, w_vec, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2, w_vec_proposal_sd)
}

fnSampEtaVec <- function(eta_vec, param_vec, w_vec, lambda_vec, c_vec, u_2, upsilon, b_eta_2) {
    .Call(`_bnpzimnr_fnSampEtaVec`, eta_vec, param_vec, w_vec, lambda_vec, c_vec, u_2, upsilon, b_eta_2)
}

fnLogMeanConstraintPrior <- function(param, psi_vec, eta_vec, w_vec, upsilon, u_2) {
    .Call(`_bnpzimnr_fnLogMeanConstraintPrior`, param, psi_vec, eta_vec, w_vec, upsilon, u_2)
}

fnSampC <- function(param, psi_vec, w_vec, eta_vec, upsilon, u_2) {
    .Call(`_bnpzimnr_fnSampC`, param, psi_vec, w_vec, eta_vec, upsilon, u_2)
}

fnSampCVec <- function(c_vec, d_vec, param_vec, psi_vec, w_vec, eta_vec, upsilon, u_2) {
    .Call(`_bnpzimnr_fnSampCVec`, c_vec, d_vec, param_vec, psi_vec, w_vec, eta_vec, upsilon, u_2)
}

fnSampLambdaVec <- function(lambda_vec, param_vec, c_vec, w_vec, eta_vec, upsilon, u_2) {
    .Call(`_bnpzimnr_fnSampLambdaVec`, lambda_vec, param_vec, c_vec, w_vec, eta_vec, upsilon, u_2)
}

fnRtkLogLik <- function(r_ik, mu_ik_vec, s_vec, lambda_ik, eta_ell, w_ell, upsilon_r, u_2, y_ik_vec, delta_ik_vec) {
    .Call(`_bnpzimnr_fnRtkLogLik`, r_ik, mu_ik_vec, s_vec, lambda_ik, eta_ell, w_ell, upsilon_r, u_2, y_ik_vec, delta_ik_vec)
}

fnSampRVec <- function(r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, Delta_mat, r_vec_proposal_sd) {
    .Call(`_bnpzimnr_fnSampRVec`, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, Delta_mat, r_vec_proposal_sd)
}

fnSjTildeLogLik <- function(s_j, mu_j_vec, rep_K, y_j_vec, delta_j_vec, h_scal, kappa_2) {
    .Call(`_bnpzimnr_fnSjTildeLogLik`, s_j, mu_j_vec, rep_K, y_j_vec, delta_j_vec, h_scal, kappa_2)
}

fnSampSVec <- function(s_vec, Mu_mat, rep_K, Y_mat, Delta_mat, h_scal, kappa_2, s_vec_proposal_sd) {
    .Call(`_bnpzimnr_fnSampSVec`, s_vec, Mu_mat, rep_K, Y_mat, Delta_mat, h_scal, kappa_2, s_vec_proposal_sd)
}

fnSampSigma2 <- function(Param_mat, Param_star_mat, C_mat, a_param, b_param) {
    .Call(`_bnpzimnr_fnSampSigma2`, Param_mat, Param_star_mat, C_mat, a_param, b_param)
}

fnGetMuJVecProp <- function(k, mu_j_vec_curr, theta_kj_curr, theta_kj_prop, r_vec, alpha_j_vec, condition, subject) {
    .Call(`_bnpzimnr_fnGetMuJVecProp`, k, mu_j_vec_curr, theta_kj_curr, theta_kj_prop, r_vec, alpha_j_vec, condition, subject)
}

fnSampThetaMat <- function(Theta_mat, Mu_mat, C_theta_mat, Theta_star_mat, Delta_mat, sigma_2_theta_vec, s_vec, r_vec, Alpha_mat, Y_mat, condition, subject, B_mat, Delta_sum_mat, theta_kj_proposal_sd) {
    .Call(`_bnpzimnr_fnSampThetaMat`, Theta_mat, Mu_mat, C_theta_mat, Theta_star_mat, Delta_mat, sigma_2_theta_vec, s_vec, r_vec, Alpha_mat, Y_mat, condition, subject, B_mat, Delta_sum_mat, theta_kj_proposal_sd)
}

fnSampThetaMatMarg <- function(Theta_mat, Mu_mat, psi_theta_vec, Theta_star_mat, Delta_mat, sigma_2_theta_vec, s_vec, r_vec, Alpha_mat, Y_mat, condition, subject, B_mat, Delta_sum_mat, theta_kj_proposal_sd) {
    .Call(`_bnpzimnr_fnSampThetaMatMarg`, Theta_mat, Mu_mat, psi_theta_vec, Theta_star_mat, Delta_mat, sigma_2_theta_vec, s_vec, r_vec, Alpha_mat, Y_mat, condition, subject, B_mat, Delta_sum_mat, theta_kj_proposal_sd)
}

fnAprxEql <- function(x, y) {
    .Call(`_bnpzimnr_fnAprxEql`, x, y)
}

fnAcceptProposal <- function(curr_log_lik, prop_log_lik, log_curr_to_prop_prob = 0, log_prop_to_curr_prob = 0) {
    .Call(`_bnpzimnr_fnAcceptProposal`, curr_log_lik, prop_log_lik, log_curr_to_prop_prob, log_prop_to_curr_prob)
}

fnMuMatCorrect <- function(Mu_mat, Delta_mat, r_vec, Alpha_mat, Theta_mat, rep_K, subject, condition, Xtbeta_mat_ = NULL) {
    invisible(.Call(`_bnpzimnr_fnMuMatCorrect`, Mu_mat, Delta_mat, r_vec, Alpha_mat, Theta_mat, rep_K, subject, condition, Xtbeta_mat_))
}

